name:                minerva32
version:             0.1.0.0
#github:              "hesiod/minerva32"
license:             Apache-2.0
author:              "Tobias Markus"
maintainer:          "tobias@miglix.eu"
copyright:           "Tobias Markus 2018"

extra-source-files:
- README.md

synopsis:            RV32I CPU built on Clash
category:            Hardware

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
#description:         Please see the README on GitHub at <https://github.com/hesiod/rv32#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: hdl
  dependencies:
  - clash-prelude
  - data-default-class
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - deepseq
  exposed-modules:
  - Types
  - Stage.InstrFetch
  - Stage.InstrDecode
  - Stage.Execute
  - Stage.Writeback
  - Top

tests:
  goldy:
    main: Test.hs
    source-dirs:
    - test
    dependencies:
    - minerva32
    - clash-prelude
    - tasty
    - tasty-golden
    - binary
    - bytestring
